import { css } from '@emotion/react';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import Layout from '../../components/Layout';
import {
  heroSection,
  heroSectionHeading,
  heroSectionHeadingImageContainer,
  heroSectionImage,
  imageContainer,
  tilesContainer,
} from '../../styles/styles';
import { Errors, Mood, Tile } from '../../util/types';

type Props = {
  username?: string;
  moods: Mood;
  tiles: Tile;
  errors: Errors[];
  day: string;
};

export default function SingleTile(props: Props) {
  const router = useRouter();

  if ('errors' in props) {
    return <div>Error: {props.errors[0].message}</div>;
  }

  if (!props.username) {
    return <div>no user passed</div>;
  }

  return (
    <Layout username={props.username}>
      {' '}
      <Head>
        <title>Detailed Tile View {props.tiles.day}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section css={heroSection}>
        <div css={heroSectionHeadingImageContainer}>
          <div css={heroSectionHeading}>
            <div css={tilesContainer}>
              <h2>Single Tile Page for {props.tiles.day}</h2>
              <div>Captured Mood: {props.moods.id}</div>
              <div>Achievements: {props.tiles.achievements}</div>
              <div>Gratitude: {props.tiles.gratitude}</div>
            </div>
          </div>
          <div css={heroSectionImage}>
            <img
              src="../../images/A-Human/tile_walking.svg"
              alt="Walking girl"
            />
          </div>
        </div>
      </section>
    </Layout>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { getValidSessionByToken, getMood } = await import(
    '../../util/database'
  );

  // Authorization: Allow only logged-in users
  const isValidSession = await getValidSessionByToken(
    context.req.cookies.sessionToken,
  );
  const sessionToken = context.req.cookies.sessionToken;

  if (!isValidSession) {
    return {
      redirect: {
        permanent: false,
        destination: '/login?returnTo=/dashboard',
      },
    };
  }
  const baseUrl = process.env.BASE_URL;
  const tileResponse = await fetch(
    `${baseUrl}/api/dashboard/${context.query.tileId}`,
    {
      method: 'GET',
      headers: {
        cookie: `sessionToken=${sessionToken}`,
      },
      credentials: 'include',
    },
  );
  const tiles = await tileResponse.json();
  const moods = await getMood();

  return {
    props: { userId: isValidSession.userId, tiles, moods },
  };
}
