import { css } from '@emotion/react';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { AllTiles } from '../../components/AllTiles';
import Layout from '../../components/Layout';
import {
  headingStyle,
  heroSection,
  heroSectionHeading,
  heroSectionHeadingImageContainer,
} from '../../styles/styles';
import { getMood } from '../../util/database';
import { Tile } from '../../util/types';

const singleTileContainer = css`
  background-image: linear-gradient(180deg, #6eb9e4 0%, #abd3cf 100%);
  border-radius: 10px;
  box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 15px 0px;
  padding: 20px;
`;

const tileGrid = css`
  display: grid;
  grid-template-rows: repeat(3, 1fr);
  grid-template-columns: repeat(3, 1fr);
  grid-gap: 30px;
  a {
    display: block;
    text-align: center;
    text-decoration: none;
    padding: 80px;
  }
`;

type Props = {
  username?: string;
  firstName?: string;
  moods: Mood[];
  userId: number;
  tiles: Tile[];
};

type Mood = {
  id: number;
  title: string;
};

export default function Tiles(props: Props) {
  const [errors, setErrors] = useState<any[]>();
  const [day, setDay] = useState('');
  const router = useRouter();
  // console.log(props);
  return (
    <Layout username={props.username}>
      <div>
        <Head>
          <title>Tiles</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div css={heroSection}>
          <div css={heroSectionHeadingImageContainer}>
            <div>
              <div css={headingStyle}>
                <h2 className="header1-text">
                  Welcome to your Dashboard, {props.firstName}
                </h2>

                <h2>Create a new entry below:</h2>

                <form
                  onSubmit={async (event) => {
                    event.preventDefault();
                    console.log(props.userId);

                    const response = await fetch(`/api/dashboard/create`, {
                      method: 'POST',
                      headers: {
                        'Content-Type': 'application/json',
                      },
                      // send request body to API route
                      body: JSON.stringify({
                        day: day,
                        userId: props.userId,
                        moodId: Number(event.currentTarget.mood.value),
                        achievements: event.currentTarget.achievements.value,
                        gratitude: event.currentTarget.gratitude.value,
                      }),
                    });

                    const tileResponseJson = await response.json();
                    console.log(tileResponseJson);

                    // Check if there is an errorMessage inside the json and update state
                    if ('errors' in tileResponseJson) {
                      setErrors(tileResponseJson.errors);
                      return;
                    }
                    router.reload();
                  }}
                >
                  <div>
                    <label htmlFor="date-picker">
                      <h2>Select date for entry</h2>
                    </label>
                  </div>
                  <input
                    type="date"
                    placeholder="30/11/2021"
                    value={day}
                    min="2021-11-01"
                    max="2022-12-31"
                    required
                    onChange={(event) => {
                      setDay(event.currentTarget.value);
                    }}
                  />

                  <div>
                    <label htmlFor="gratitude">
                      <h2>Set your mood for the day</h2>
                    </label>
                  </div>
                  <select id="mood" name="mood">
                    <option value="">Select Mood</option>
                    {props.moods.map((mood) => {
                      return (
                        <option key={mood.id} value={mood.id}>
                          {mood.title}
                        </option>
                      );
                    })}
                  </select>
                  <div>
                    <label htmlFor="achievements">
                      <h2>What are you aiming to achieve today?</h2>
                    </label>
                  </div>
                  <div>
                    <textarea
                      name="achievements"
                      placeholder="What are you aiming to achieve today?"
                      max-length="10000"
                    />
                  </div>
                  <div>
                    <label htmlFor="gratitude">
                      <h2>What are you grateful for today?</h2>
                    </label>
                  </div>
                  <div>
                    <textarea
                      name="gratitude"
                      placeholder="What are your grateful for"
                      max-length="10000"
                    />
                  </div>
                  <div>
                    <button className="button-general">
                      Create daily entry
                    </button>
                  </div>
                </form>
              </div>
              <div>
                <h2>Your Tile Overview</h2>
              </div>
              <button>Filter</button>
              <div css={tileGrid}>
                {props.tiles.map((tile) => {
                  return (
                    <div key={`tile-li-${tile.id}`} css={singleTileContainer}>
                      <div>
                        <Link passHref href={`/dashboard/${tile.id}`}>
                          <h2>
                            <a>{tile.day}</a>
                          </h2>
                        </Link>
                        Achievements: {tile.achievements}
                        <p />
                        Grateful for: {tile.gratitude}
                        <p />
                      </div>
                      <div>
                        {/* TO-DO Delete tile functionality */}
                        <button
                          className="button-general"
                          onClick={async (event) => {
                            event.preventDefault();
                            if (
                              !window.confirm(
                                `Are you sure you want to delete this tile? This cannot be reversed!`,
                              )
                            ) {
                              return;
                            }

                            const response = await fetch(
                              `/api/dashboard/${tile.id}`,
                              {
                                method: 'DELETE',
                                headers: {
                                  'Content-Type': 'application/json',
                                },
                                body: JSON.stringify({
                                  day: day,
                                  userId: props.userId,
                                  moodId: moodId,
                                  achievements: achievements,
                                  gratitude: gratitude,
                                }),
                              },
                            );

                            await response.json();

                            // Reload page after tile has been deleted
                            router.reload();
                          }}
                        >
                          Delete
                        </button>
                        <button>Edit</button>
                        <button>Forward by Email</button>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { getValidSessionByToken } = await import('../../util/database');

  // Authorization: Allow only logged-in users
  const isValidSession = await getValidSessionByToken(
    context.req.cookies.sessionToken,
  );
  const sessionToken = context.req.cookies.sessionToken;

  if (!isValidSession) {
    return {
      redirect: {
        permanent: false,
        destination: '/login?returnTo=/dashboard',
      },
    };
  }
  const baseUrl = process.env.BASE_URL;
  const tileResponse = await fetch(`${baseUrl}/api/dashboard/`, {
    method: 'GET',
    headers: {
      cookie: `sessionToken=${sessionToken}`,
    },
    credentials: 'include',
  });
  const tiles = await tileResponse.json();
  const moods = await getMood();

  return {
    props: { moods, userId: isValidSession.userId, tiles },
  };
}
